production:
  solr:
    hostname: localhost
    port: 7973
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 7972
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 7971
    log_level: WARNING
    path: /solr/test